# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'techExploration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for techExploration
  pod 'GoogleMLKit/ObjectDetection', '3.2.0'

  target 'techExplorationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'techExplorationUITests' do
    # Pods for testing
  end

end
